antigen bundle git
antigen bundle pip
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle cp
antigen bundle sudo
antigen bundle colored-man-pages
antigen bundle command-not-found
antigen bundle djui/alias-tips
antigen bundle aliases
antigen bundle ansible
