keys:
  - &wsl age1svwaalg5zhfvfu43v9nmm9r8s9rgwyv6sgt55ylwkqccwjxscqsqne3dlr
  - &gig age12p8lr30zx8q6ml3ehpfa96hefxs48zas3p7ktl9p804r57a3tgvs2s0k85
  - &buzz age184sdwkr3876f498etmjkeyu6r0huudql4t8ktwwwatlwm24u5uasmfsskc
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *wsl
        - *gig
        - *buzz
