antigen bundle git
antigen bundle pip
antigen bundle cp
antigen bundle sudo
antigen bundle colored-man-pages
antigen bundle command-not-found
antigen bundle aliases
antigen bundle ansible
antigen bundle virtualenvwrapper
antigen bundle copybuffer
