{ inputs, pkgs, ... }:
# Custom hardware overrides for ganoslal multi-GPU 6-monitor setup
# This file imports the original autogenerated hardware-configuration.nix
# and adds multi-GPU support and overrides
{
  imports = [
    ./hardware-configuration.nix # Import original autogenerated file
    ./nvidia.nix # NVIDIA-specific configuration

    # nixos-hardware modules for proper hardware detection
    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-gpu-nvidia-nonprime
    inputs.nixos-hardware.nixosModules.common-gpu-amd
  ];

  # Override/add AMD GPU support for secondary display outputs
  boot = {
    initrd = {
      kernelModules = [ "amdgpu" ]; # Enable AMD GPU kernel modules
    };

    # Enable audio drivers for HDMI/DisplayPort output from GPUs
    kernelModules = [ "snd-hda-intel" ];

    # Updated kernel parameters for better AMD/NVIDIA coexistence
    kernelParams = [
      "radeon.si_support=0" # Disable legacy radeon driver for SI cards
      "amdgpu.si_support=1" # Enable amdgpu driver for SI cards
      "nvidia-drm.modeset=1" # Enable NVIDIA DRM modesetting
      "amdgpu.dc=1" # Enable AMD Display Core for better multi-monitor
      "amdgpu.dpm=1" # Enable AMD dynamic power management
      "amdgpu.runpm=0" # Disable runtime power management to prevent crashes
      "amdgpu.bapm=0" # Disable bidirectional application power management
    ];
  };

  services = {
    # Audio configuration for multi-GPU setup
    pulseaudio.enable = false; # Disable PulseAudio in favor of PipeWire
    pipewire = {
      enable = true;
      alsa = {
        enable = true;
        support32Bit = true;
      };
      pulse.enable = true;
      # Enable additional audio codecs for better compatibility
      extraConfig.pipewire."92-low-latency" = {
        context.properties = {
          default.clock = {
            rate = 48000;
            quantum = 32;
            min-quantum = 32;
            max-quantum = 32;
          };

          # Environment variables for better multi-GPU compatibility
          environment.variables = {
            # Force AMD GPU to use newer DRM interface
            AMD_VULKAN_ICD = "RADV";
            # Help X11 with multi-GPU detection
            __GL_SHADER_DISK_CACHE_PATH = "/tmp";
            __GL_THREADED_OPTIMIZATIONS = "1";
          };

          # Hardware acceleration and graphics configuration
          hardware = {
            graphics = {
              enable = true;
              enable32Bit = true;
              extraPackages = with pkgs; [
                # AMD GPU support (mesa includes RADV driver automatically)
                mesa
                # NVIDIA support
                libva
                libva-utils
              ];
            };
          };
        };
      };
    };

    # X11 multi-GPU configuration with explicit screen fallbacks
    xserver = {
      # Enable both GPU drivers in priority order (NVIDIA primary, AMD secondary)
      videoDrivers = [
        "nvidia"
        "amdgpu"
      ];

      # Explicit X11 configuration to handle multi-GPU setup and prevent "no screens found"
      config = ''
        Section "ServerLayout"
            Identifier     "Layout0"
            Screen      0  "Screen0" 0 0
            Screen      1  "Screen1" RightOf "Screen0"
            Option         "Xinerama" "0"
        EndSection

        Section "Monitor"
            Identifier     "Monitor0"
            Option         "DPMS"
        EndSection

        Section "Monitor"
            Identifier     "Monitor1"
            Option         "DPMS"
        EndSection

        Section "Device"
            Identifier     "Device0"
            Driver         "nvidia"
            VendorName     "NVIDIA Corporation"
            BusID          "PCI:1:0:0"
            Option         "NoLogo" "true"
            Option         "UseDisplayDevice" "none"
        EndSection

        Section "Device"
            Identifier     "Device1"
            Driver         "amdgpu"
            VendorName     "AMD"
            BusID          "PCI:12:0:0"
            Option         "TearFree" "true"
        EndSection

        Section "Screen"
            Identifier     "Screen0"
            Device         "Device0"
            Monitor        "Monitor0"
            DefaultDepth    24
            Option         "Stereo" "0"
            Option         "nvidiaXineramaInfoOrder" "DFP-5"
            Option         "metamodes" "nvidia-auto-select +0+0"
            Option         "SLI" "Off"
            Option         "MultiGPU" "Off"
            Option         "BaseMosaic" "off"
            SubSection     "Display"
                Depth       24
            EndSubSection
        EndSection

        Section "Screen"
            Identifier     "Screen1"
            Device         "Device1"
            Monitor        "Monitor1"
            DefaultDepth    24
            SubSection     "Display"
                Depth       24
            EndSubSection
        EndSection
      '';

      # Additional X11 settings for multi-GPU
      extraConfig = ''
        Section "Extensions"
            Option         "GLX" "Disable"
        EndSection
      '';
    };
  };
}
