{ ... }:
# Custom hardware overrides for ganoslal multi-GPU 6-monitor setup
# This file imports the original autogenerated hardware-configuration.nix
# and adds multi-GPU support and overrides
{
  imports = [
    ./hardware-configuration.nix # Import original autogenerated file
    ./nvidia.nix # NVIDIA-specific configuration
  ];

  # Override/add AMD GPU support for secondary display outputs
  boot = {
    initrd = {
      kernelModules = [ "amdgpu" ]; # Enable AMD GPU kernel modules
    };

    # AMD kernel parameters for GCN1 (Southern Island) cards compatibility
    kernelParams = [
      "radeon.si_support=0" # Disable legacy radeon driver for SI cards
      "amdgpu.si_support=1" # Enable amdgpu driver for SI cards
    ];
  };

  # Multi-GPU X server configuration for 6-monitor setup
  services.xserver = {
    # Enable both GPU drivers - NVIDIA remains primary due to Prime configuration
    videoDrivers = [
      "nvidia"
      "amdgpu"
    ];

    # Multi-monitor X server configuration
    config = ''
      Section "ServerLayout"
        Identifier "MultiGPU"
        Screen 0 "nvidia"
        Screen 1 "amd" RightOf "nvidia"
        Option "Xinerama" "1"
      EndSection

      Section "Monitor"
        Identifier "Monitor0"
        Option "Primary" "true"
      EndSection

      Section "Monitor"
        Identifier "Monitor1"
      EndSection

      Section "Monitor"
        Identifier "Monitor2"
      EndSection

      Section "Monitor"
        Identifier "Monitor3"
      EndSection

      Section "Monitor"
        Identifier "Monitor4"
      EndSection

      Section "Monitor"
        Identifier "Monitor5"
      EndSection

      Section "Device"
        Identifier "nvidia"
        Driver "nvidia"
        BusID "PCI:45:0:0"
        Option "AllowExternalGpus" "True"
      EndSection

      Section "Device"
        Identifier "amd"
        Driver "amdgpu"
        BusID "PCI:23:0:0"
        Option "TearFree" "true"
      EndSection

      Section "Screen"
        Identifier "nvidia"
        Device "nvidia"
        Monitor "Monitor0"
        DefaultDepth 24
        SubSection "Display"
          Depth 24
        EndSubSection
      EndSection

      Section "Screen"
        Identifier "amd"
        Device "amd"
        Monitor "Monitor1"
        DefaultDepth 24
        SubSection "Display"
          Depth 24
        EndSubSection
      EndSection
    '';
  };
}
