{ inputs, ... }:
# Custom hardware overrides for ganoslal multi-GPU 6-monitor setup
# This file imports the original autogenerated hardware-configuration.nix
# and adds multi-GPU support and overrides
{
  imports = [
    ./hardware-configuration.nix # Import original autogenerated file
    ./nvidia.nix # NVIDIA-specific configuration

    # nixos-hardware modules for proper hardware detection
    inputs.nixos-hardware.nixosModules.common-cpu-amd
    inputs.nixos-hardware.nixosModules.common-gpu-nvidia-nonprime
    inputs.nixos-hardware.nixosModules.common-gpu-amd
  ];

  # Override/add AMD GPU support for secondary display outputs
  boot = {
    initrd = {
      kernelModules = [ "amdgpu" ]; # Enable AMD GPU kernel modules
    };

    # Enable audio drivers for HDMI/DisplayPort output from GPUs
    kernelModules = [ "snd-hda-intel" ];

    # Updated kernel parameters for better AMD/NVIDIA coexistence
    kernelParams = [
      "radeon.si_support=0" # Disable legacy radeon driver for SI cards
      "amdgpu.si_support=1" # Enable amdgpu driver for SI cards
      "nvidia-drm.modeset=1" # Enable NVIDIA DRM modesetting
      "amdgpu.dc=1" # Enable AMD Display Core for better multi-monitor
    ];
  };

  # Audio configuration for multi-GPU setup
  hardware.pulseaudio.enable = false; # Disable PulseAudio in favor of PipeWire
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # Enable additional audio codecs for better compatibility
    extraConfig.pipewire."92-low-latency" = {
      context.properties = {
        default.clock.rate = 48000;
        default.clock.quantum = 32;
        default.clock.min-quantum = 32;
        default.clock.max-quantum = 32;
      };
    };
  };

  # Simplified X server configuration for automatic monitor detection
  services.xserver = {
    # Enable both GPU drivers - let them handle monitors independently
    videoDrivers = [
      "nvidia"
      "amdgpu"
    ];
    # Remove manual X11 config - let modern drivers auto-detect monitors
  };
}
