# GanosLal Host Configuration
# This is your system's configuration file.
# Use this to configure your system environment (it replaces /etc/nixos/configuration.nix)
{
  inputs,
  lib,
  config,
  configLib,
  ...
}:
{
  # You can import other NixOS modules here
  imports = [
    # If you want to use modules from other flakes (such as nixos-hardware):
    # inputs.hardware.nixosModules.common-cpu-amd
    # inputs.hardware.nixosModules.common-ssd

    # You can also split up your configuration and import pieces of it here:
    # ./users.nix

    # Import your generated (nixos-generate-config) hardware configuration
    ./bare-metal/hardware-configuration.nix
    
    # Core utils
    (configLib.relativeToRoot "hosts/common/core")

    # Optional modules (uncomment as needed)
    # (configLib.relativeToRoot "hosts/common/optional/gui.nix")
    # (configLib.relativeToRoot "hosts/common/optional/firefox.nix")
    # ../common/optional/xrdp.nix

    # Gig user configuration
    (configLib.relativeToRoot "hosts/common/users/gig")

    # WiFi support
    (configLib.relativeToRoot "hosts/common/optional/wifi.nix")

    # Bootloader configuration
    (configLib.relativeToRoot "hosts/common/core/bootloader.nix")
  ];

  networking = {
    hostName = "ganosLal";
    # hostId should be a unique 8-character (hexadecimal) string, especially if using ZFS.
    # You can generate one with: head -c4 /dev/urandom | od -An -tx1 | tr -d ' \n'
    hostId = "a1b2c3d4"; # TODO: Generate unique hostId during setup
  };

  # Bootloader configuration for dual-boot with Windows
  bootloader.kind = "systemd-boot"; # or "grub" for dual-boot compatibility

  nix =
    let
      flakeInputs = lib.filterAttrs (_: lib.isType "flake") inputs;
    in
    {
      settings = {
        # Enable flakes and new 'nix' command
        experimental-features = "nix-command flakes";
        # Opinionated: disable global registry
        flake-registry = "";
        # Workaround for https://github.com/NixOS/nix/issues/9574
        nix-path = config.nix.nixPath;
      };
      # Opinionated: disable channels
      channel.enable = false;

      # Opinionated: make flake registry and nix path match flake inputs
      registry = lib.mapAttrs (_: flake: { inherit flake; }) flakeInputs;
      nixPath = lib.mapAttrsToList (n: _: "${n}=flake:${n}") flakeInputs;
    };

  # TODO: Configure filesystems after running disko
  # Example ZFS configuration (will be generated by disko):
  # fileSystems = {
  #   "/" = {
  #     device = "zroot/root";
  #     fsType = "zfs";
  #   };
  #   "/boot" = {
  #     device = "/dev/disk/by-uuid/BOOT-UUID"; # Will be set by disko
  #     fsType = "vfat";
  #   };
  #   "/nix/store" = {
  #     device = "zroot/nix";
  #     fsType = "zfs";
  #   };
  # };

  # https://nixos.wiki/wiki/FAQ/When_do_I_update_stateVersion
  system.stateVersion = "25.05";
}