# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    initrd = {

      availableKernelModules = [
        "nvme"
        "ahci"
        "xhci_pci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ "amdgpu" ];
    };
    kernelModules = [ "kvm-amd" ];

    # AMD GPU page on nixos wiki:
    # https://nixos.wiki/wiki/AMD_GPU

    kernelParams = [
      # needed for GCN1 (Southern Island) cards i.e. my shitty second AMD card
      "radeon.si_support=0"
      "amdgpu.si_support=1"
    ];
    extraModulePackages = [ ];
  };
  fileSystems = {

    "/" = {
      device = "/dev/disk/by-uuid/14e6d54a-d136-4e87-a04a-6f0585960aad";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/D47B-8DEC";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/18dd5063-c9bc-4db5-bf9e-1bbec5435e25"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp39s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
