# Carried over from GeeM-Enterprises/dot-spacedock during the spacedock
# onboarding (dotfiles#14).
#
# ⚠️  REGENERATE THIS FILE on the actual spacedock box before switching:
#     `nixos-generate-config --show-hardware-config > hosts/spacedock/hardware-configuration.nix`
# The values below (disk UUID, kernel modules, broadcom-sta pin) are a faithful
# snapshot of the last-known dot-spacedock hardware and are expected to drift.
#
# Original header:
# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "ehci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [
    "kvm-intel"
    "wl"
  ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9c984e82-15a1-41dc-8695-f8a74e5cab44";
    fsType = "ext4";
  };

  nixpkgs.config.permittedInsecurePackages = [
    "broadcom-sta-6.30.223.271-57-6.12.41"
  ];

  swapDevices = [ ];

  # Networking is configured in hosts/common/core + hosts/spacedock/default.nix
  # networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
